version: '3.3'

services:
  template_node_ts:
    image: template_node_ts
    ports:
      - 3000:3000
    command: "npm run dev"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile    
    volumes:
      - ./:/home/app
      - /home/app/node_modules